#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    . /lib/functions.sh
    config_load lrapServer
    config_get listen     server listen ':9080'
    config_get ubus_url   server ubus_url 'http://127.0.0.1/ubus'
    config_get cors       server cors_origin '*'
    config_get tls_cert   server tls_cert ''
    config_get tls_key    server tls_key  ''

    procd_open_instance
    procd_set_param command /usr/sbin/lrapServer/lrapServer
    procd_set_param env LISTEN_ADDR="$listen" UBUS_URL="$ubus_url" CORS_ORIGIN="$cors" TLS_CERT_FILE="$tls_cert" TLS_KEY_FILE="$tls_key"
    procd_set_param respawn 3600 5 5  
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
